dist: focal
language: python
python:
  - "3.11"

install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    - EB_APP_NAME="djangosite"
    - EB_ENV_NAME="django-app-env"
    - COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN


before_script:
  - black --check .
  - flake8 --max-line-length=88

script:
  - coverage run --source='.' manage.py test
  - coverage report

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: $EB_APP_NAME
  env: $EB_ENV_NAME
  bucket_name: "elasticbeanstalk-us-west-2-523272053639"
  skip_cleanup: true
  on:
    branch: main

after_success:
  - coveralls
